[
    [
        916657, 
        "dnf remove wants to downgrade packages; fails on transaction check"
    ], 
    [
        921294, 
        "dnf downgrade failure"
    ], 
    [
        922521, 
        "DNF crashes when passing packages to it via pipe"
    ], 
    [
        926871, 
        "[abrt] download_packages:AttributeError: 'Repo' object has no attribute 'cache'"
    ], 
    [
        878826, 
        "[rfe] dnf could use systemd timer unit rather than crontabs"
    ], 
    [
        922664, 
        "an option for disabling the regular metadata sync"
    ], 
    [
        892064, 
        "hourly dnf makecache too frequent, also consider using ionice"
    ], 
    [
        919769, 
        "dnf runs makecache hourly despite laptop power state"
    ], 
    [
        947258, 
        "dnf doesn't erase excluded packages"
    ], 
    [
        889202, 
        "[rfe] [repos] add support for skip_if_unavailable in repository config"
    ], 
    [
        923384, 
        "DNF uses yum web signature"
    ], 
    [
        950722, 
        "[abrt] dnf-0.3.2-1.gitf3818b4.fc20: queries.py:179:_construct_result:AttributeError: 'NoneType' object has no attribute 'query'"
    ], 
    [
        903775, 
        "Update command is deprecated but nomenclature still being used"
    ], 
    [
        887317, 
        "Dnf should beter report upgrades via obsoletes."
    ], 
    [
        914919, 
        "DNF does not have   group install"
    ], 
    [
        922667, 
        "the cronned 'dnf makecache' runs should give up quickly if there's network/checksumming issues"
    ], 
    [
        958452, 
        "dnf update Produces Log Messages Involving \"ts_done state\""
    ], 
    [
        959990, 
        "dnf dist-sync recommended in manual page but is missing from dnf's command line options"
    ], 
    [
        961549, 
        "[abrt] dnf-0.3.4-1.git03fd687.fc19: __init__.py:826:perform:Exception: (10, 'Error HTTP/FTP status code: 404', 404)"
    ], 
    [
        962188, 
        "obsoletes sometimes result in \"ERROR with transaction check vs depsolve\""
    ], 
    [
        966372, 
        "dnf prints an empty python list after running without root privileges"
    ], 
    [
        965410, 
        "\"dnf clean expire-cache\" does not have any effect"
    ], 
    [
        963627, 
        "dnf shows way over 100% in its progress bar"
    ], 
    [
        965114, 
        "When running dnf using file:/// as the media, it tries to erase packages in file:///"
    ], 
    [
        964467, 
        "group install is broken"
    ], 
    [
        963680, 
        "dnf dies with a traceback during update"
    ], 
    [
        963133, 
        "name is misprinted when package is not found"
    ], 
    [
        916662, 
        "dnf remove wants to install new packages"
    ], 
    [
        967732, 
        "[abrt] dnf-0.3.6-1.git24ce938.fc19: __init__.py:364:hashopen:DBNoSuchFileError: (2, 'Datei oder Verzeichnis nicht gefunden')"
    ], 
    [
        908491, 
        "[rfe] list recent"
    ], 
    [
        968159, 
        "repo_rpmmd.c: base:xml attr in <location> is ignored"
    ], 
    [
        974427, 
        "dnf fails on all commands with fatal error: \"global name 'os' is not defined\""
    ], 
    [
        974866, 
        "dnf crashes if neither baseurl nor mirrorlist are defined"
    ], 
    [
        976652, 
        "[abrt] UnicodeEncodeError with 'dnf info checkpolicy'"
    ], 
    [
        975858, 
        "dnf can't install in an empty installroot"
    ], 
    [
        964584, 
        "dnf doesn't replace $releasever/$basearch in mirror url"
    ], 
    [
        979942, 
        "[abrt] cli.py:1015:_configure_repos:KeyError: <repo id>"
    ], 
    [
        980227, 
        "[locking] OSError when a long running transaction gets metadata files written over by a concurrent 'dnf makecache'"
    ], 
    [
        981310, 
        "NameError: global name 'to_utf8' is not defined"
    ], 
    [
        977661, 
        "[abrt] Ctrl+C ends up with a TypeError traceback involving Base.__exit__() and Repo._handle_load()"
    ], 
    [
        984483, 
        "default to skip_if_unavailable=True"
    ], 
    [
        986545, 
        "dnf mismatching it's librepo dep in rawhide"
    ], 
    [
        979042, 
        "Slow download of packages"
    ], 
    [
        977753, 
        "Repository \"@System\" instead of \"fedora\""
    ], 
    [
        996138, 
        "[abrt] install_grouplist:UnicodeDecodeError during 'dnf group install'"
    ], 
    [
        993916, 
        "'upgrade' command displays old version numbers in summary, rather than new version numbers"
    ], 
    [
        997403, 
        "Error message instructs users to invoke 'yum' rather than 'dnf' to fix a problem"
    ], 
    [
        1002508, 
        "Updated to install any packages \"An Curl handle error: Unsupported protocol\""
    ], 
    [
        1002798, 
        "Error when checking librepo explicit requires"
    ], 
    [
        998859, 
        "\"dnf upgrade --best\" will always install 64bits package when 32bit package is installed"
    ], 
    [
        1006366, 
        "dnf makecache runs on LiveCD"
    ], 
    [
        1008444, 
        "confusing message when removing packages"
    ], 
    [
        1003220, 
        "[abrt] dnf-0.3.11-1.git7d717c7.fc19: output.py:838:_enc:TypeError: object of type 'NoneType' has no len()"
    ], 
    [
        909744, 
        "[rfe] support parallel downloads"
    ], 
    [
        984529, 
        "[rfe] fastest mirror"
    ], 
    [
        967798, 
        "[RFE] repositories costs"
    ], 
    [
        995459, 
        "conflicting requests when trying to install locally available packages"
    ], 
    [
        1013764, 
        "DNF group remove doesn't work"
    ], 
    [
        1013773, 
        "DNF group info doesn't work"
    ], 
    [
        1017278, 
        "dnf does not notice file conflicts"
    ], 
    [
        1021087, 
        "traceback during download after a transaction with obsoletes"
    ], 
    [
        878348, 
        "'dnf history undo' support missing"
    ], 
    [
        880524, 
        "[kernel] managing multiple kernel packages"
    ], 
    [
        1019957, 
        "'dnf groups summary' traceback (global name 'patterns' is not defined)"
    ], 
    [
        1020101, 
        "'dnf grouplist' throws NameError"
    ], 
    [
        1020934, 
        "traceback in \"dnf repolist\""
    ], 
    [
        1023486, 
        "groups operations failing due to a libcomps API change in its latest version (KeyError: 'en_US.UTF-8')"
    ], 
    [
        1019170, 
        "handling wildcards in the version"
    ], 
    [
        1024776, 
        "librepo version mismatch (no attribute 'LRO_FASTESTMIRRORCACHE')"
    ], 
    [
        1025650, 
        "[abrt] dnf-0.4.6-1.fc20: i18n.py:119:ucd:UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 51: ordinal not in range(128)"
    ], 
    [
        1014563, 
        "Support Python 3 in DNF"
    ], 
    [
        1029948, 
        "dnf does not show all desktop environments in dnf groups list output"
    ], 
    [
        1030998, 
        "install doesn't work for '*/binaryname' patterns"
    ], 
    [
        1030297, 
        "dnf doesn't support http urls"
    ], 
    [
        1030980, 
        "dnf downgrade PACKAGE, misleading message about possible typo if PACKAGE is not installed"
    ], 
    [
        884615, 
        "RFE: Provide list of packages installed on top of the system"
    ], 
    [
        963137, 
        "[rfe] perform complex packaging operations as a CLI user"
    ], 
    [
        991038, 
        "lacks history rollback"
    ], 
    [
        1032455, 
        "[abrt] dnf-0.4.7-1.fc20: decoder.py:383:raw_decode:ValueError: No JSON object could be decoded"
    ], 
    [
        1034607, 
        "dnf does not work with media repo"
    ], 
    [
        1036116, 
        "dnf install failed with exception"
    ], 
    [
        967264, 
        "[plugins] Support post-transaction actions"
    ], 
    [
        1018284, 
        "[rfe] [api] refactor check for valid id into separate function"
    ], 
    [
        1035164, 
        "[abrt] dnf-0.4.7-1.fc20: miscutils.py:61:checkSig:OSError: [Errno 2] Adres\u00e1\u0159 nebo soubor neexistuje: '/var/cache/dnf/x86_64/20/updates-testing/packages/kernel-3.11.9-300.fc20.x86_64.rpm'"
    ], 
    [
        1036147, 
        "[locking] Traceback for dnf search if running under su - USER"
    ], 
    [
        1036211, 
        "Install groups using @ sign"
    ], 
    [
        1038403, 
        "[abrt] dnf-0.4.9-1.fc20: base.py:1832:handle_erase:AssertionError"
    ], 
    [
        1038937, 
        "[plugins] [api] Add hook for metadata download complete event"
    ], 
    [
        1040255, 
        "dnf show wrong Installed size when  install  packages"
    ], 
    [
        1044502, 
        "[abrt] dnf: base.py:125:_add_repo_to_sack:UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 113: ordinal not in range(128)"
    ], 
    [
        1044981, 
        "[doc] [rfe] support setopt"
    ], 
    [
        1044999, 
        "[doc] show dependencies during update"
    ], 
    [
        1048402, 
        "[abrt] dnf: cli.py:1521:search:AttributeError: 'module' object has no attribute 'exception'"
    ], 
    [
        1048572, 
        "dnf resolve failure"
    ], 
    [
        1048716, 
        "man page does not mention sub command remove"
    ], 
    [
        1048719, 
        "Minor error in 'dnf --help', using the package name Yum instead of dnf"
    ], 
    [
        1048988, 
        "[plugins] [api] add a hook for MD refresh"
    ], 
    [
        1045737, 
        "[RFE] 'throttle' option."
    ], 
    [
        1048468, 
        "dnf --cacheonly list installed tries to download repodata"
    ], 
    [
        1048488, 
        "AssertionError on invalid error log level"
    ], 
    [
        1049025, 
        "Incorrect dependency check on removal"
    ], 
    [
        1051554, 
        "disable fastestmirror by default (and make it configurable)"
    ], 
    [
        909468, 
        "[rfe] delta rpm support"
    ], 
    [
        1030440, 
        "[RFE] bash completion support"
    ], 
    [
        1046244, 
        "dnf doesn't keep the downloaded packages in the cache"
    ], 
    [
        1055051, 
        "things like ' dnf install \"kernel-devel-uname-r = 3.12.8-300.fc20.x86_64\" ' don't work"
    ], 
    [
        1056400, 
        "DNF not support url installation for a package"
    ], 
    [
        1062390, 
        "dnf.rpmUtils.arch.getBaseArch() doesn't return identical results to yum's rpmUtils.arch.getBaseArch()"
    ], 
    [
        1062847, 
        "dnf man page errors"
    ], 
    [
        1063022, 
        "[abrt] dnf: i18n.py:38:write:UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 12: ordinal not in range(128)"
    ], 
    [
        1064148, 
        "DNF attempts to remove packages from local file-based repository"
    ], 
    [
        1048788, 
        "[abrt] dnf: __init__.py:183:install:ArchException: Used arch is unknown."
    ], 
    [
        1065728, 
        "[doc] Metadata expire configurable per repository"
    ], 
    [
        1065879, 
        "[API] provides is missing in queries documentation"
    ], 
    [
        1065959, 
        "dnf tab completion should use \"distro-sync\" instead of \"distribution-synchronization\""
    ], 
    [
        1066743, 
        "[doc] `dnf clean` should function or warn when run as normal user"
    ], 
    [
        1069996, 
        "[abrt] dnf: repo.py:312:start:AttributeError: 'NoneType' object has no attribute 'start'"
    ], 
    [
        1059704, 
        "[api] dnf.base.Base.read_comps() fails when there's no comps"
    ], 
    [
        1058224, 
        "the system cache should be world readable by default"
    ], 
    [
        1069538, 
        "DNF doesn't support \"never\" or \"-1\" for metadata_expire option unlike yum"
    ], 
    [
        1070598, 
        "problems downloading large files (and counting past 100%)"
    ], 
    [
        1070710, 
        "dnf.Base.read_comps() fails in Python3, works ok in Python2"
    ], 
    [
        1071323, 
        "[api] [rfe]: dnf.repo & dnf.repodict API extention"
    ], 
    [
        1071455, 
        "[i18n] Wrong characters in Japanese translatated message"
    ], 
    [
        1071501, 
        "[drpm] fallback to full RPM download on drpm failure"
    ], 
    [
        1071518, 
        "curl error"
    ], 
    [
        1071677, 
        "[doc] faq suggests it's a good idea to install rawhide packages on stable releases"
    ], 
    [
        963710, 
        "RFE: allow package specs for distro-sync"
    ], 
    [
        1067136, 
        "[comps] no way to install optional packages from a group"
    ], 
    [
        1071212, 
        "dnf doesn't skip unreadable repository files"
    ], 
    [
        1077173, 
        "IOError: [Errno 13] Permission denied: '/var/lib/dnf/groups.json'"
    ], 
    [
        1078832, 
        "TypeError: '_DownloadErrors' object is not iterable"
    ], 
    [
        1079621, 
        "Incorrect package count when some packages already downloaded"
    ], 
    [
        1029022, 
        "RFE: API for reverse group operations"
    ], 
    [
        1051869, 
        "[abrt] dnf: comps.py:62:_by_pattern:TypeError: expected string or buffer"
    ], 
    [
        1061780, 
        "Dnf allows installing conflicting packages"
    ], 
    [
        1062884, 
        "[api] Allow dnf plugin to set exit code"
    ], 
    [
        1062889, 
        "[RFE] [api] add class attribute to dnf.cli.Command which will say it is root-only plugin"
    ], 
    [
        1063666, 
        "[comps] [environments] dnf group remove \"GNOME Desktop\""
    ], 
    [
        1064211, 
        "Dnf should provide logrotate script"
    ], 
    [
        1064226, 
        "[rfe] cmdline option forcing cache refresh"
    ], 
    [
        1073859, 
        "[api][rfe] access to dnf.Base.goal_parameters.allow_uninstall"
    ], 
    [
        1076884, 
        "[py3] highlight characters broken under py3"
    ], 
    [
        1079519, 
        "[api][rfe] install .rpm files with dnf API"
    ], 
    [
        1079932, 
        "[api][rfe] public api for getting all packages in a group"
    ], 
    [
        1080331, 
        "dnf group list fail to run with noroot plugin"
    ], 
    [
        1080489, 
        "[RFE] dnf exits with an error when at least one srpm is present on the command line"
    ], 
    [
        1082230, 
        "TypeError in dnf history info <id>"
    ], 
    [
        1083432, 
        "group is marked as installed, even if install of the packages failed"
    ], 
    [
        1083767, 
        "dnf documents cached packages in a way which does not agree with reality"
    ], 
    [
        1084139, 
        "dnf manpage \"manipualte\" typos"
    ], 
    [
        1084553, 
        "[doc] dnf docs describe '--best' option in undecipherabke manner"
    ], 
    [
        1088166, 
        "[doc] DNF doesn't say you need root rights to run dnf update"
    ], 
    [
        1065882, 
        "[delta] delta rpm download size statistics"
    ], 
    [
        1081753, 
        "do not emit uncaught exceptions from automatic makecache runs"
    ], 
    [
        1089864, 
        "[api] group persistor is not saved when using group_* API"
    ], 
    [
        963345, 
        "[rfe] autoremove"
    ], 
    [
        1073457, 
        "Auto-completion issue with sudo dnf install"
    ], 
    [
        1076045, 
        "[rfe] ssl support"
    ], 
    [
        1083679, 
        "dnf globbing does not really work"
    ], 
    [
        1092006, 
        "[abrt] dnf: __init__.py:1704:parse_extcmds:ValueError: need more than 0 values to unpack"
    ], 
    [
        1092777, 
        "[abrt] dnf: __init__.py:403:run:UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)"
    ], 
    [
        1093888, 
        "[search] put exact matches first"
    ], 
    [
        1094594, 
        "dnf history rollback tracebacks"
    ], 
    [
        1095580, 
        "[kernel] kernel-models-extra cannot be installed because a newer one is already installed"
    ], 
    [
        1095861, 
        "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21: ordinal not in range(128)"
    ], 
    [
        1096506, 
        "promoting 'install a' to 'install b' when b obsoletes a"
    ], 
    [
        1047049, 
        "distroverpkg default should be the same in dnf as in yum"
    ], 
    [
        1067156, 
        "[api] introspecting transaction"
    ], 
    [
        1093420, 
        "Add to dnf.conf ip_resolve entry"
    ], 
    [
        1104757, 
        "[api] yumvars not set fail fedora metadata download"
    ], 
    [
        1105009, 
        "Please update the queries api documentation"
    ], 
    [
        1110800, 
        "[abrt] dnf: parser.py:59:varReplace:UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)"
    ], 
    [
        1111569, 
        "make \"Transaction couldn't start (no root?)\" error more clear"
    ], 
    [
        1111997, 
        "[abrt] dnf: base.py:1894:_retrievePublicKey:TypeError: not all arguments converted during string formatting"
    ], 
    [
        1112669, 
        "commands from dnf-plugins-core not mentioned in man page"
    ], 
    [
        1112704, 
        "NameError: global name 'i18n' is not defined"
    ], 
    [
        1048973, 
        "[rfe] repo priorities"
    ], 
    [
        1108908, 
        "dnf dies immediately complaining that ascii codec can't decode 0xc3"
    ], 
    [
        1116544, 
        "[i18n] double width Unicode characters"
    ], 
    [
        1116839, 
        "CompsError: Group 'Core' is already installed."
    ], 
    [
        1116845, 
        "dnf crashed when executing 'dnf -v repolist all'"
    ], 
    [
        1117102, 
        "[doc] configuring plugin search directories"
    ], 
    [
        1117293, 
        "--installroot proceeds with an undefined conf.releasever"
    ], 
    [
        1117678, 
        "[py3] proper binary for python3-dnf"
    ], 
    [
        1118178, 
        "should create /etc/dnf/plugins directory"
    ], 
    [
        1118796, 
        "TypeError: must be unicode, not str"
    ], 
    [
        1119032, 
        "python3-dnf-0.5.3 conflicts with  dnf-0.5.2"
    ], 
    [
        1100946, 
        "dnf install <bin filename> installs both i686 and x86_64 packages for no reason"
    ], 
    [
        1117789, 
        "[doc] [api] custom repos"
    ], 
    [
        1120583, 
        "[api] full-featured proxy configuration"
    ], 
    [
        1121280, 
        "History list with login names fails with non-ascii names"
    ], 
    [
        1122900, 
        "[abrt] dnf: package.py:73:header:RuntimeError: (Rpm file does not exist)"
    ], 
    [
        1123688, 
        "dnf missing Requires on pyliblzma"
    ], 
    [
        850912, 
        "RFE: support updateinfo"
    ], 
    [
        1055910, 
        "[rfe] includepkgs directive support"
    ], 
    [
        1116666, 
        "handling groups installed by Yum"
    ], 
    [
        1118272, 
        "search command show traceback when in a debug mode"
    ], 
    [
        1127206, 
        "[abrt] dnf: __init__.py:186:install:Exception: Goal operation failed."
    ], 
    [
        1132335, 
        "RFE [UX] - Give users hint on uknown command"
    ], 
    [
        1071854, 
        "dnf reinstall does not work as expected"
    ], 
    [
        1131969, 
        "[rfe] group_install: accepts package specs as excludes"
    ], 
    [
        908764, 
        "RFE: Support repo-pkgs command set"
    ], 
    [
        1130878, 
        "[abrt] dnf: persistor.py:60:_diff_dcts:AttributeError: 'NoneType' object has no attribute 'keys'"
    ], 
    [
        1130432, 
        "[abrt] dnf: locale.py:166:_group:UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)"
    ], 
    [
        1118236, 
        "dnf doesn't seem to support repo_gpgcheck config"
    ], 
    [
        1109915, 
        "[rfe] yum-cron replacement"
    ], 
    [
        909856, 
        "[rfe] lazy mode for metadata syncing"
    ], 
    [
        1134893, 
        "\"dnf update\" works as \"dnf install\" on local package files"
    ], 
    [
        1138700, 
        "dnf doesn't install all packages on command line"
    ], 
    [
        1070902, 
        "dnf autocomplete for install ./* + <TAB> takes ages"
    ], 
    [
        1124316, 
        "[locking] per-installroot metadata lock"
    ], 
    [
        1136584, 
        "[abrt] dnf: rpmsack.py:255:_read:AttributeError: <dnf.yum.rpmsack.RPMDBAdditionalDataPackage object at 0x7f10fed01b50> has no attribute reason"
    ], 
    [
        1135861, 
        "group erase libreoffice fails, package requires but none of the providers can be installed"
    ], 
    [
        1136223, 
        "[abrt] dnf: packages.py:76:parsePackages:TypeError: unsupported operand type(s) for |=: 'set' and 'list'"
    ], 
    [
        1122617, 
        "reinstall of local rpms gives traceback"
    ], 
    [
        1133830, 
        "Does not import gpg keys"
    ], 
    [
        1121184, 
        "dnf: shows fake download speed when not downloading anything"
    ], 
    [
        1153543, 
        "dnf bash completion hangs when trying to complete local path"
    ], 
    [
        1151231, 
        "Broken bash completion (does not occur when dnf-plugins-core installed)"
    ], 
    [
        1163063, 
        "dnf install with glob pattern output should be similar to yum install with glob"
    ], 
    [
        1151854, 
        "--cacheonly is not being respected \u2013 will update the cache if expired"
    ], 
    [
        1151740, 
        "dnf base api should not use errorSummary from dnf.cli.BaseCli"
    ], 
    [
        1110780, 
        "dnf swap not supported"
    ], 
    [
        1149972, 
        "update command implicitly working as reinstall"
    ], 
    [
        1150474, 
        "dnf group install broken for locale other than en_US"
    ], 
    [
        995537, 
        "RFE: /etc/motd emitter for yum-cron"
    ], 
    [
        1149952, 
        "Python exception thrown when searching dnf history"
    ], 
    [
        1149350, 
        "Odd placement and no rotation of hawkey.log"
    ], 
    [
        1170232, 
        "dnf eats newlines from error message"
    ], 
    [
        1147523, 
        "missing group info environment group support"
    ], 
    [
        1148208, 
        "[rfe] enable deltarpm support by default"
    ], 
    [
        1109927, 
        "RFE: take systemd inhibitor lock while doing operations that shouldn't be interrupted by shutdown"
    ], 
    [
        1155877, 
        "[abrt] dnf: i18n.py:130:ucd:UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)"
    ], 
    [
        1175466, 
        "add timeout option to repo conf"
    ], 
    [
        1186461, 
        "\"file\" filter in DNF"
    ], 
    [
        1170156, 
        "[RFE][UX] Display metadata timestamp"
    ], 
    [
        1184943, 
        "please enrich DNF API with a method for setting up base.conf.cachedir for non privileged users"
    ], 
    [
        1177002, 
        "comps display_order for environment groups not respected by installer with dnf payload (or dnf itself)"
    ], 
    [
        1169165, 
        "let glob pattern describing package to match multiple packages"
    ], 
    [
        1167982, 
        "dnf.conf man page is in the wrong section"
    ], 
    [
        1157233, 
        "'dnf download' cannot be run in parallel as non-root user"
    ], 
    [
        1138096, 
        "[doc] add examples on install, resolve, do_transaction api usage"
    ], 
    [
        1181189, 
        "dnf downgrade ./<TAB> doesn't autocomplete"
    ], 
    [
        1181397, 
        "[abrt] dnf: output.py:683:_display_packages_verbose:KeyError: u'ppc64-utils'"
    ], 
    [
        1175434, 
        "Odd placement and no rotation of hawkey.log"
    ], 
    [
        1162887, 
        "[api] introspecting transaction package sets"
    ], 
    [
        1156084, 
        "dnf install @some-environment-id does not work"
    ], 
    [
        1175098, 
        "dnf: unowned dir /etc/dnf/protected.d"
    ], 
    [
        1174136, 
        "wrongly computed text width with nonascii characters"
    ], 
    [
        1155918, 
        "let \"history list\" show all records"
    ], 
    [
        1119030, 
        "skip_if_unavailable to correctly treat repos that are down during package download"
    ], 
    [
        1177394, 
        "Dnf specifies both \"size\" and an age in the logrotate configuration"
    ], 
    [
        1154476, 
        "[abrt] dnf: lock.py:64:_read_lock:ValueError: invalid literal for int() with base 10: ''"
    ], 
    [
        1203151, 
        "Duplicated output for already installed packages"
    ], 
    [
        1187579, 
        "dnf upgrade ./<TAB> doesn't autocomplete"
    ], 
    [
        1185977, 
        "[api] remove cached package file only after transaction()"
    ], 
    [
        1195240, 
        "dnf-automatic \"how to use\""
    ], 
    [
        1193914, 
        "'help history' does not correspond with supported commands"
    ], 
    [
        1195385, 
        "dnf regression: cannot resolve provides with slashes"
    ], 
    [
        1160806, 
        "DNF shoud not deprecate \"remove\" command"
    ], 
    [
        1186710, 
        "dnf --setopt exclude=XXX adds garbage to excludes"
    ], 
    [
        1207726, 
        "Update dnf and yum packages for proposed dnf default change"
    ], 
    [
        1190671, 
        "DNF ships bash completition file but lacks requirement on bash completion"
    ], 
    [
        1191579, 
        "python3-dnf cannot be used without python2"
    ], 
    [
        1195325, 
        "RFE: provide a way to configure the config directory used by plugins"
    ], 
    [
        1154202, 
        "[depsolv] removing a package results in downloading more packages"
    ], 
    [
        1189083, 
        "[doc] please document 'skip_if_unavailable' Repo flag"
    ], 
    [
        1193915, 
        "[abrt] dnf: output.py:1730:historySummaryCmd:ValueError: need more than 0 values to unpack"
    ], 
    [
        1195661, 
        "lock files cannot be created for non logged users"
    ], 
    [
        1190458, 
        "[abrt] dnf: cli.py:210:do_transaction:UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf3' in position 196: ordinal not in range(128)"
    ], 
    [
        1194685, 
        "CACHEDIR_SUFFIX appended twice to cachedir when using dnf CLI."
    ], 
    [
        1160950, 
        "\"dnf install foo.rpm\" doesn't upgrade \"foo\""
    ], 
    [
        1199648, 
        "[UX] dnf groupinstall claims that installed group does not exist"
    ], 
    [
        1208773, 
        "[RFE] Define virtual provides for DNF commands and suggest installing the appropriate one if a command was not found"
    ], 
    [
        1208018, 
        "config-manager: enable won't work. TypeError: unorderable types: Repo() < Repo()"
    ], 
    [
        1207861, 
        "Python 3: historical transactions that had multiple problems causes tracebacks"
    ], 
    [
        1201445, 
        "\"dnf autoremove\" removes \"user-installed\" installonly packages installed using \"dnf upgrade\""
    ], 
    [
        1210275, 
        "DNF doesn't support http authentication"
    ], 
    [
        1191275, 
        "dnf downgrade <target-nevra> fails"
    ], 
    [
        1207965, 
        "Improve yum deprecated message"
    ], 
    [
        1215560, 
        "[abrt] dnf: i18n.py:165:exact_width:TypeError: 'NoneType' object is not iterable"
    ], 
    [
        1215289, 
        "bash completion file adds a shell alias for python"
    ], 
    [
        1214968, 
        "dnf reports installed group does not exist"
    ], 
    [
        1222694, 
        "[abrt] python-dnf: comps.py:86:install_or_skip:TypeError: unsupported operand type(s) for +=: 'int' and 'TransactionBunch'"
    ], 
    [
        1225246, 
        "yum2dnf manpage: too much underlining"
    ], 
    [
        1213985, 
        "[rfe] add equivalent of \"random_sleep\" to dnf-automatic"
    ], 
    [
        1225277, 
        "python(abi) = 3.3 is needed by (installed)"
    ], 
    [
        1223932, 
        "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 19: ordinal not in range(128)"
    ], 
    [
        1223614, 
        "dnf groupinstall fails and returns success"
    ], 
    [
        1203661, 
        "[CRY] sslclientcert and sslclientkey not supported"
    ], 
    [
        1187741, 
        "dnf should state if packages explicitly requested for update aren't installed"
    ], 
    [
        1148630, 
        "add --allowerasing hint for conflict problems"
    ], 
    [
        1176351, 
        "[RFC] print warning message when we're going to install not latest version"
    ], 
    [
        1210445, 
        "[rfe] report when skipping available updates due to dependency reasons"
    ], 
    [
        1173107, 
        "mock: use of \"dnf --installroot ...\" yields \"releasever not given\" error"
    ], 
    [
        1219199, 
        "Problem when using proxy authentication in dnf.conf"
    ], 
    [
        1220040, 
        "[abrt] python-dnf: completion_helper.py:92:run:UnboundLocalError: local variable 'pkgs' referenced before assignment"
    ], 
    [
        1230975, 
        "[rfe] configurable parallel downloads (like yum's max_connections)"
    ], 
    [
        1232815, 
        "'dnf install @group' returns error code 1 if all packages are already installed"
    ], 
    [
        1113384, 
        "[rfe] repofrompath option to specify ad-hoc repo"
    ], 
    [
        1133979, 
        "yum/dnf --quiet option not working for check-update command"
    ], 
    [
        1238958, 
        "dnf-automatic fails to send mail"
    ], 
    [
        1238252, 
        "Typo in dnf man page"
    ], 
    [
        1212320, 
        "[metadata] dnf makecache never timeouts"
    ], 
    [
        1218401, 
        "[doc] document history_list_view and set it to cmd by default"
    ], 
    [
        1227952, 
        "dnf update on a local directory does not handle mutliple versions of the same package"
    ], 
    [
        1197456, 
        "[RFE] implement `strict` config option (defaults=True)"
    ], 
    [
        1236310, 
        "dnf --quiet repolist doesn't output anything"
    ], 
    [
        1219638, 
        "DNF doesn't use xml:base in repodata"
    ], 
    [
        1207981, 
        "[UX] error during unpacking archive does not fail the installation"
    ], 
    [
        1208918, 
        "RFE: dnf shouldn't stop processing the command line at the first unknown package"
    ], 
    [
        1221635, 
        "add dnf config option to (not)obey weak deps"
    ], 
    [
        1236306, 
        "Some of dnf's subcommands can't handle pipe"
    ], 
    [
        1234639, 
        "dnf package actions triggered by dnf-automatic aren't logged to dnf.rpm.log"
    ], 
    [
        1244486, 
        "[doc] Add yum vs dnf hooks information in dnf documentation"
    ], 
    [
        1224248, 
        "[UX] Error message doesn't show names of packages well"
    ], 
    [
        1243501, 
        "`dnf downgrade' treats installed packages as not installed"
    ], 
    [
        1225237, 
        "[UX] [doc] FILES section missing from manual pages"
    ], 
    [
        1249319, 
        "dnf says \"downloaded packages were saved in cache\" before actually downloading any packages"
    ], 
    [
        1234763, 
        "wildcard in dnf update/downgrade should match installed packages only"
    ], 
    [
        1242946, 
        "[depsolv] dnf prefers package names over provide names"
    ], 
    [
        1225225, 
        "[abrt] python-dnf: repo.py:774:load:RepoError: Cache-only enabled but no cache for 'fedora'"
    ], 
    [
        1254687, 
        "DNF does not display any translations"
    ], 
    [
        1247766, 
        "dnf logrotate.d rotates logs too fast in many cases"
    ], 
    [
        1125925, 
        "[RFE] provide a 'add to user-installed-list' command"
    ], 
    [
        1210289, 
        "RFE: Have a way to wait on dnf lock rather than terminate"
    ], 
    [
        1262082, 
        "'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)"
    ], 
    [
        1250038, 
        "[abrt] python-dnf: completion_helper.py:84:run:IndexError: list index out of range"
    ], 
    [
        1048433, 
        "RFE --downloadonly"
    ], 
    [
        1259650, 
        "\"dnf provides\" or \"dnf repoquery --whatprovides\" does not support globs"
    ], 
    [
        1260198, 
        "python-dnf should provide python2-dnf"
    ], 
    [
        1259657, 
        "No dnf-command() provides for dnf commands"
    ], 
    [
        1254982, 
        "dnf-automatic generates emails with broken charset"
    ], 
    [
        1261766, 
        "RFE: way to force no metadata expiration system-wide"
    ], 
    [
        1234491, 
        "[UX] dnf list installed: show repo id the package was installed from"
    ], 
    [
        1256531, 
        "dnf install crashes if terminal window is too small"
    ], 
    [
        1261656, 
        "DNF group update doesn't work"
    ], 
    [
        1258364, 
        "Some important dnf output goes to STDERR and not to STDOUT"
    ], 
    [
        1278031, 
        "dnf fails to find system-upgrade plugin with certain locales (Chinese, Japanese and maybe more)"
    ], 
    [
        1264032, 
        "RFE: add \"Skipped\" into Transaction Summary"
    ], 
    [
        1209056, 
        "[UX] [TRANS] Plural strings are not extracted properly"
    ], 
    [
        1274946, 
        "[abrt] dnf: main.py:99:main:IOError: [Errno 5] Input/output error"
    ]
]